=== FreeBSD Foundation

Links: +
link:https://www.FreeBSDfoundation.org[FreeBSD Foundation] URL: link:https://www.FreeBSDfoundation.org[https://www.FreeBSDfoundation.org] +
link:https://freebsdfoundation.org/blog/technology-roadmap/[Technology Roadmap] URL: link:https://freebsdfoundation.org/blog/technology-roadmap/[https://freebsdfoundation.org/blog/technology-roadmap/] +
link:https://www.FreeBSDfoundation.org/donate/[Donate] URL: link:https://www.FreeBSDfoundation.org/donate/[https://www.FreeBSDfoundation.org/donate/] +
link:https://www.FreeBSDfoundation.org/FreeBSD-foundation-partnership-program/[Foundation Partnership Program] URL: link:https://www.FreeBSDfoundation.org/FreeBSD-foundation-partnership-program[https://www.FreeBSDfoundation.org/FreeBSD-foundation-partnership-program] +
link:https://www.FreeBSDfoundation.org/journal/[FreeBSD Journal] URL: link:https://www.FreeBSDfoundation.org/journal/[https://www.FreeBSDfoundation.org/journal/] +
link:https://www.FreeBSDfoundation.org/news-and-events/[Foundation News and Events] URL: link:https://www.FreeBSDfoundation.org/news-and-events/[https://www.FreeBSDfoundation.org/news-and-events/] +

Contact: Deb Goodkin <deb@FreeBSDFoundation.org>

The FreeBSD Foundation is a 501(c)(3) non-profit organization dedicated to
supporting and promoting the FreeBSD Project and community worldwide. Donations
from individuals and corporations are used to fund and manage software
development projects, conferences, and developer summits. We also provide travel
grants to FreeBSD contributors, purchase and support hardware to improve and
maintain FreeBSD infrastructure, and provide resources to improve security,
quality assurance, and release engineering efforts. We publish marketing
material to promote, educate, and advocate for the FreeBSD Project, facilitate
collaboration between commercial vendors and FreeBSD developers, and finally,
represent the FreeBSD Project in executing contracts, license agreements, and
other legal arrangements that require a recognized legal entity.

Here are some highlights of what we did to help FreeBSD last quarter:

==== Fundraising Efforts


You’ll find out how we used your donations here and in individual entries
throughout this status report.

We’re passionate about supporting you, the FreeBSD community, but we can’t do it
without your financial support.  Please consider making a donation to help us
continue and increase our support for FreeBSD in 2021:
link:https://www.FreeBSDfoundation.org/donate/[https://www.FreeBSDfoundation.org/donate/].

We also have the Partnership Program, to provide more benefits for our larger
commercial donors. Find out more information at
link:https://www.FreeBSDfoundation.org/FreeBSD-foundation-partnership-program/[https://www.FreeBSDfoundation.org/FreeBSD-foundation-partnership-program/]
and share with your companies!

==== OS Improvements

During the fourth quarter, Foundation staff and grant recipients committed ???
src tree changes, ??? ports tree changes, and ?? doc tree changes. This
represents ??%, ??%, and ??% of src, port, and doc commits which identify a
sponsor.

You can read about Foundation-sponsored projects in individual quarterly report
entries:


Foundation-sponsored arm64 work:

==== Continuous Integration and Quality Assurance

The Foundation provides a full-time staff member and funds projects to improve
continuous integration, automated testing, and overall quality assurance efforts
for the FreeBSD project.

See the separate Continuous Integration entry for details.

==== Supporting FreeBSD Infrastructure


==== Partnerships and Commercial User Support


==== FreeBSD Advocacy and Education


We help educate the world about FreeBSD by publishing the professionally
produced FreeBSD Journal. As we mentioned previously, the FreeBSD Journal is now
a free publication. Find out more and access the latest issues at
link:https://www.FreeBSDfoundation.org/journal/[https://www.FreeBSDfoundation.org/journal/].

You can find out more about events we attended and upcoming events at
link:https://www.FreeBSDfoundation.org/news-and-events/[https://www.FreeBSDfoundation.org/news-and-events/].

==== Legal/FreeBSD IP

The Foundation owns the FreeBSD trademarks, and it is our responsibility to
protect them. We also provide legal support for the core team to investigate
questions that arise.

Go to link:https://www.FreeBSDfoundation.org[https://www.FreeBSDfoundation.org]
to find more about how we support FreeBSD and how we can help you!
