== Base System OpenSSH update

Links: +
link:https://www.openssh.com/[OpenSSH] URL: https://www.openssh.com/ +
link:https://lists.freebsd.org/pipermail/freebsd-security/2021-September/010473.html[Mailing list posting] URL: https://lists.freebsd.org/pipermail/freebsd-security/2021-September/010473.html

Contact: Ed Maste <emaste@freebsd.org>

OpenSSH is a suite of remote login and file transfer servers and client
tools.  OpenSSH in the base system has been updated from version 7.9p1 to
8.7p1.

We have a number of local bug fixes, configuration changes, and small features
in our base system version of OpenSSH.  As part of the work for this update
I submitted some of these upstream, and am preparing to do the same with the
remaining ones.

OpenSSH now supports FIDO/U2F devices, although additional work is required
to enable this in the FreeBSD base system.  This includes importing a pair
of dependencies: libcbor, and libfido2.

Within the next couple of months I expect to enable FIDO/U2F support, and
update to OpenSSH version 8.8p1.

NOTE: OpenSSH 8.8p1 will disable the ssh-rsa signature scheme by default,
so some additional work is required for this next update.  For more information
please see the
link:https://lists.freebsd.org/pipermail/freebsd-security/2021-September/010473.html[Important note for future FreeBSD base system OpenSSH update]
mailing list post.

Sponsor: The FreeBSD Foundation
